### ISSUE TITLE
Delete Account API

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#469]
**Is your feature request related to a problem? Please describe.**
Users should be able to delete accounts. This would be used by the Wallet screen in Textile Photos

**Describe the solution you'd like**
An API for deleting accounts. Is it possible? Does it make sense?

**Comment by sanderpick** [comment]
I _think_ this just means wipe the local repo for the account and deregister w/ cafes. Related to a number of existing issues like #475 #310

**Comment by andrewxhill** [comment]
What happens if currently if you init with a new seed? Would the old repo linger around?

**Comment by sanderpick** [comment]
If you used the same repo dir, you'd just get an error saying something like "bailing, re-initializing would wipe your repo". If diff repo dir, all good - old one lingers next to it.

**Comment by andrewxhill** [comment]
Okay, that's cool. So if we supported this in the rn library, i could get around this by just having the client delete the repo first.

**Comment by sanderpick** [comment]
Nice, sounds good

**Comment by andrewxhill** [comment]
okay... working through this scenario

1. i have an 'account' on Photos. and the same account on Desktop.
2. i `deregister` account in my Photos app. meaning it will ping the Cafe(s) and tell them to forget me.
3. I `delete` the account in my Photos app. meaning the local repo will be wiped.

I think the expected behavior here would be that the Desktop copy of the account would remain. But if it was using the same cafe it would suddenly get an error saying it old cafe was no longer valid or something?

Sound right?

**Comment by sanderpick** [comment]
Right, but the cafes are not connected

**Comment by sanderpick** [comment]
To clarify, the cafe sessions are at the peer level. So, a peer can only de-register itself. Other sessions, whether on the same cafe or not, need to also de-register.

That said, we could add account deletion to the "account peer" level control messages: https://docs.textile.io/concepts/threads/#account-sync
