### ISSUE TITLE
Move to single-use (symmetric) keys in threads

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#605]
In the past, we used to do some signing with the thread key-pairs, which required asymmetric encryption (private/public keys). However, we don't need to do this anymore, and we already generate symmetric keys for other uses, which are more efficient. Let's move to using these everywhere.
This is probably a pretty fast change (says the person who probably won't have to do it), and for compatibility, we could do something like: try to unmarshal into ed25519, and if that fails try AES.

**Comment by sanderpick** [comment]
We currently use the inline ed25519 keys in which we get a public ID for free (view libp2p-crypto). The inlining won't be relevant anymore since we won't have a public key, but we'll still need a deterministic way to derive a public ID out of these symmetric keys. I _think_ we could just hash and encode it (`base58(sha-256)`), basically same as before?
