### ISSUE TITLE
Custom annotations for folders, subfolders, trash, starring

### ISSUE THREAD

**Issue by leshokunin** [textileio/go-textile#711]
We’re working on folder support for Epona.
We’ve been thinking about making threads for folders, and have links to other threads for sub folders, with threads for the pages we have in the folders.

We’ve also considered having special folders for starred items (with a link to the pages and folders that have been starred), and a trash (for links to items that have been added to the trash).

The problem is that when we have multiple attributes (item is in this folder, and starred, and trashed), it doesn’t make sense to have this kind of hierarchy.

Would there be a way to make annotations that would be compatible with how you see the path forward for Textile?

**Comment by sanderpick** [comment]
I think you're on the right path with the idea of having threads for a user's starred items. These are _for the user_, rather than something like a star annotation in a shared thread. In that sense, it is less like an annotation and more like a categorization. 

I don't quite understand the trash bin. You could visualize the "ignored" content in a thread.

**Comment by carsonfarmer** [comment]
Closing as no longer relevant in Threads v2
