### ISSUE TITLE
Write CafeHTTPRequest body to file

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#737]
Background uploads are only supported for file-based data. This makes sense because the app may be terminated during an upload, and therefore all the app’s memory goes away. We need to write the request payloads to disk and `CafeHTTPRequest` should just have a property that is the path to the file.

**Comment by sanderpick** [comment]
Moved to this sprint (11).

I guess we'll have to make an assumption about who is doing the queue handling since on mobile we'll have to write them to disk.

An option to get around that is to do the writing when the handler calls `SetCafeRequestPending`, or if that timing does't work, just another method, `WriteCafeRequest` or something.

**Comment by sanderpick** [comment]
Oh, nvm, I guess we just write the data to disk when the handler calls `CafeHTTPRequest`.

**Comment by sanderpick** [comment]
Do you want the file deleted when `SetCafeRequestComplete` is called?

**Comment by asutula** [comment]
Seems like a good time to delete it, yea.

**Comment by asutula** [comment]
It's not clear to me yet what "cleanup" is all about. It's something you mentioned needs to be called.

**Comment by sanderpick** [comment]
Cleanup check to see if a group can be deleted. It's just more efficient to allow the handler to call this rather than internally every time a req is marked as complete.
