### ISSUE TITLE
npm install -g @textileio/go-textile

### ISSUE THREAD

**Issue by balupton** [textileio/go-textile#848]
Installing go-textile at the ipfs camp workshop meant:

1. Getting users to navigate to our github
2. Click `go-textile` repo
3. Click releases
4. Download the binary for their machine
5. Unzip it
6. Place it somewhere in their path, or execute manually

It would be much nicer if it was as simple as `npm install -g @textileio/go-textile`

We can use https://github.com/bevry/safeps to identify if `textile` is already in the PATH, as well as to indentify the version. We can also use this package to fetch `go-textile` from IPFS, in case the internet is down, as well as to cache the binaries. We can also use this package to perform regular version checks.

**Comment by carsonfarmer** [comment]
Initial prototype going on here: https://github.com/carsonfarmer/get-go-textile, but is missing functionality and is largely just a fork of https://github.com/ipfs/npm-go-ipfs-dep.

**Comment by sanderpick** [comment]
The binary should live under GOPATH. Why not just make `go install github.com/textileio/go-textile` work like it should?

**Comment by carsonfarmer** [comment]
The reason for the above prototype is actually so that you can build JS apps that leverage the binary locally... in the case of an electron app, you'd want the binary packaged _with_ the Electron app, rather than externally (this would allow us to make `desktop` a pure electron app that could fetch updates to the underlying daemon without having to install a whole new app).

**Comment by balupton** [comment]
> The binary should live under GOPATH. Why not just make `go install github.com/textileio/go-textile` work like it should?

This also requires that they already have go setup and configured

**Comment by leshokunin** [comment]
Hey guys, sorry to pop in, but this is actually the most important work there is for us on the roadmap.

Basically, now that we have releases built automatically with CircleCI, I want to make the step to start using Permaweb Writer as easy as possible. Right now, having people download go-textile is a bad hurdle.

I'd love it if we could bundle the Textile node with our release. So that you can just click the program and run it. It'd take care of running the node in the background (check if you already have one), and it'd run.

Would love if it can happen!

**Comment by carsonfarmer** [comment]
Fixed with https://github.com/textileio/npm-go-textile-dep
